--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HakanBabus/HologramAPI
build-by-default: true
branches:
- main
projects:
  HologramAPI:
    path: ""
    model: virion
    type: library
...
